In [1]:
import numpy as np
import random
import gym

# Create an environment

In [2]:
env = gym.make("FrozenLake-v0")

# To cheack environment states and action

In [3]:
action = env.action_space.n
state = env.observation_space.n

In [4]:
print("number of actions", action)

number of actions 4


In [5]:
print("number of state", state)

number of state 16


# Create qtable and initialize the table

In [7]:
qtable = np.zeros((state,action))

In [8]:
qtable

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

# Create parameters

In [14]:
episodes = 10000
lr = 0.85
max_steps = 99
gamma = 0.95


#Explorations
epsilon = 1.0
max_epsilon = 1.0 
min_epsilon = 0.01
decay_rate = 0.005

In [16]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + lr * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/episodes))
print(qtable)

Score over time: 0.4419
[[  1.91679051e-01   5.02668452e-02   1.94700009e-01   7.76884208e-02]
 [  9.77027823e-03   2.90919943e-03   4.21152203e-03   2.31158817e-02]
 [  9.62997898e-03   1.81143553e-02   7.07021242e-03   1.85451271e-02]
 [  2.68365583e-03   4.29450979e-03   1.51821137e-02   1.73175181e-02]
 [  2.21818990e-01   3.74298325e-02   1.76068451e-03   3.56745627e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.68939815e-04   5.54732503e-04   1.83892155e-02   1.10015013e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.08671696e-03   8.01265340e-03   1.15477247e-02   3.95098684e-01]
 [  3.89113906e-03   6.79986404e-01   4.52865203e-03   2.71176833e-03]
 [  9.18699291e-01   1.53343279e-04   7.79298551e-04   7.52878249e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.69758915e-03   1.44122362e-03   8.75656509e-01 

In [18]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("----------------------------------------------------------->")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

----------------------------------------------------------->
EPISODE  0
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 46
----------------------------------------------------------->
EPISODE  1
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 66
----------------------------------------------------------->
EPISODE  2
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 15
----------------------------------------------------------->
EPISODE  3
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 7
----------------------------------------------------------->
EPISODE  4
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 7
